fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() == "windows" {
        // Only run winres on Windows targets
        // The logo.ico will be generated by the GitHub action pipeline before compilation
        if std::path::Path::new("assets/logo.ico").exists() {
            let mut res = winres::WindowsResource::new();
            res.set_icon("assets/logo.ico");
            if let Err(e) = res.compile() {
                println!("cargo:warning=Failed to compile Windows resources: {}", e);
            }
        }
    }
}
